services:
   back:
      platform: linux/amd64
      container_name: medusa-back
      image: dockerhub.graphandco.com/medusa-back:latest
      build:
         context: .
         dockerfile: Dockerfile
         tags:
            - dockerhub.graphandco.com/medusa-back:1.0.0
            - dockerhub.graphandco.com/medusa-back:latest
      restart: unless-stopped
      env_file:
         - .env.production
      environment:
         NODE_ENV: production
         REDIS_URL: redis://redis-cache:6379
         MEDUSA_WORKER_MODE: shared
      networks:
         - web-network
      cpus: 1
      mem_limit: 1g
      security_opt:
         - no-new-privileges:true
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: "3"

networks:
   web-network:
      external: true
