FROM node:22-alpine

RUN apk add --no-cache python3 make g++ \
  && npm install -g pnpm@10.11.1

WORKDIR /server

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json .npmrc ./
COPY apps/backend/package.json ./apps/backend/
COPY apps/storefront/package.json ./apps/storefront/

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 9000 5173

CMD ["sh", "./start-dev.sh"]
