FROM node:22-alpine

RUN npm install -g pnpm@10.11.1

WORKDIR /server

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json .npmrc ./
COPY apps/backend/package.json ./apps/backend/
COPY apps/storefront/package.json ./apps/storefront/

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 8000

CMD ["pnpm", "--filter", "@dtc/storefront", "dev"]
